
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author k00245120
 */
public class AlgorithmAndDataStructreJFrame extends javax.swing.JFrame {

    LinkedQueue queue = new LinkedQueue();

    /**
     * Creates new form AlgorithmAndDataStructreJFrame
     */
    public AlgorithmAndDataStructreJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        printJButton = new javax.swing.JButton();
        clearJButton = new javax.swing.JButton();
        reverseJButton = new javax.swing.JButton();
        removeDataJButton = new javax.swing.JButton();
        addDataJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayJTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        printJButton.setText("Print");
        printJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printJButtonActionPerformed(evt);
            }
        });

        clearJButton.setText("Clear ");
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });

        reverseJButton.setText("Reverse");
        reverseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reverseJButtonActionPerformed(evt);
            }
        });

        removeDataJButton.setText("Remove data");
        removeDataJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDataJButtonActionPerformed(evt);
            }
        });

        addDataJButton.setText("Add data");
        addDataJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDataJButtonActionPerformed(evt);
            }
        });

        displayJTextArea.setColumns(20);
        displayJTextArea.setRows(5);
        jScrollPane1.setViewportView(displayJTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reverseJButton)
                    .addComponent(printJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearJButton)
                    .addComponent(removeDataJButton)
                    .addComponent(addDataJButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printJButton)
                    .addComponent(addDataJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reverseJButton)
                    .addComponent(removeDataJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearJButton)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDataJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDataJButtonActionPerformed
        // TODO add your handling code here:
        String data = JOptionPane.showInputDialog("enter data");
        queue.append(data);
        displayJTextArea.setText("entered " + data + " into the queue");

    }//GEN-LAST:event_addDataJButtonActionPerformed

    private void removeDataJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDataJButtonActionPerformed
        // TODO add your handling code here:
        if (!queue.isEmpty()) {

            Object data = queue.serve();
            displayJTextArea.setText("removed " + data + " into the queue");
        } else
            displayJTextArea.setText("queue is empty");
    }//GEN-LAST:event_removeDataJButtonActionPerformed

    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        // TODO add your handling code here:
        queue.clear();
        displayJTextArea.setText("cleared the queue");

    }//GEN-LAST:event_clearJButtonActionPerformed

    private void printJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printJButtonActionPerformed
        // TODO add your handling code here:
        String anyNameUnderTheSun = queue.print();
        displayJTextArea.setText(anyNameUnderTheSun);
    }//GEN-LAST:event_printJButtonActionPerformed

    private void reverseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reverseJButtonActionPerformed
        // TODO add your handling code here:
        String anyNameUnderTheSun;

        anyNameUnderTheSun = queue.print();
        displayJTextArea.setText(anyNameUnderTheSun);
        displayJTextArea.append("\nReverse the queue\n");

        queue.reverse();
        anyNameUnderTheSun = queue.print();
        displayJTextArea.append(anyNameUnderTheSun);


    }//GEN-LAST:event_reverseJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlgorithmAndDataStructreJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlgorithmAndDataStructreJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlgorithmAndDataStructreJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlgorithmAndDataStructreJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlgorithmAndDataStructreJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDataJButton;
    private javax.swing.JButton clearJButton;
    private javax.swing.JTextArea displayJTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printJButton;
    private javax.swing.JButton removeDataJButton;
    private javax.swing.JButton reverseJButton;
    // End of variables declaration//GEN-END:variables
}
